version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  tests:
    build: .
    command: [ "pytest", "tests.py" ]
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:

